---
- name: Install Docker
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - vagrant
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
